version: '3'

services:
  #  client:
  #    container_name: client
  #    build:
  #      context: ../src/client
  #      dockerfile: Dockerfile.dev
  #    restart: unless-stopped
  #    ports:
  #      - "13000:3000"
  #    volumes:
  #      - /usr/src/app/node_modules
  #      - ../src/client:/usr/src/app
  #    depends_on:
  #      - app
  #    stdin_open: true

#  application:
#    build: ../src/backend
#    restart: unless-stopped
#    volumes:
#      - ../src/backend/target/iRide-Backend-1.0-SNAPSHOT.jar:/iRide-Backend-1.0-SNAPSHOT.jar
#    ports:
#      - "18080:8080"
#    depends_on:
#      - database

  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=school
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=schooldb
    ports:
      - "54320:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../src/psql:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a
      PGADMIN_DEFAULT_PASSWORD: a
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "28080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "database:pgsql-server"
    depends_on:
      - database


volumes:
  postgres-data:
  pgadmin-data: